# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from motor_control import MotorConfig


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(603, 305)
        Dialog.setStyleSheet("QGroupBox {\n"
"    background-color: #c0b3e6; /* Light purple background */\n"
"    border: 2px solid black;\n"
"    border-radius: 10px;\n"
"    font-weight: bold;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    border: 1px solid black;\n"
"    border-radius: 5px;\n"
"    padding: 5px 15px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #e6e6fa; /* Light lavender on hover */\n"
"}\n"
"\n"
"\n"
"QGroupBox {\n"
"    background-color: #cdbce6;  /* Soft lavender */\n"
"    border: 2px solid black;\n"
"    border-radius: 10px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QDialog {\n"
"    background-color: #cdbce6;  /* Soft lavender */\n"
"    border: 2px solid black;\n"
"    border-radius: 10px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        
        motors = MotorConfig()

        self.JogMode = QtWidgets.QGroupBox(Dialog)
        self.JogMode.setGeometry(QtCore.QRect(10, 150, 261, 141))
        self.JogMode.setStyleSheet("")
        self.JogMode.setAlignment(QtCore.Qt.AlignCenter)
        self.JogMode.setObjectName("JogMode")
        self.pushButton = QtWidgets.QPushButton(self.JogMode)
        self.pushButton.setGeometry(QtCore.QRect(90, 40, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_5 = QtWidgets.QPushButton(self.JogMode)
        self.pushButton_5.setGeometry(QtCore.QRect(250, 190, 75, 23))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.JogMode)
        self.pushButton_6.setGeometry(QtCore.QRect(340, 150, 75, 23))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.JogMode)
        self.pushButton_7.setGeometry(QtCore.QRect(350, 80, 75, 23))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.JogMode)
        self.pushButton_8.setGeometry(QtCore.QRect(90, 110, 75, 23))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.JogMode)
        self.pushButton_9.setGeometry(QtCore.QRect(170, 20, 75, 23))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("cHJpdmF0ZS9sci9pbWFnZXMvd2Vic2l0ZS8yMDI0LTExL3YxMTgxLXR1LWVsZW1lbnQtMjUwLXAtbTN3cXR3dTEucG5n.webp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_9.setIcon(icon)
        self.pushButton_9.setObjectName("pushButton_9")
        self.widget = QtWidgets.QWidget(self.JogMode)
        self.widget.setGeometry(QtCore.QRect(10, 70, 239, 27))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_4 = QtWidgets.QPushButton(self.widget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(310, 150, 281, 141))
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(20, 30, 61, 20))
        self.lineEdit.setInputMask("")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2.setGeometry(QtCore.QRect(90, 30, 61, 20))
        self.lineEdit_2.setInputMask("")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_3.setGeometry(QtCore.QRect(160, 30, 51, 20))
        self.lineEdit_3.setInputMask("")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_4.setGeometry(QtCore.QRect(90, 60, 81, 20))
        self.lineEdit_4.setInputMask("")
        self.lineEdit_4.setText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.pushButton_34 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_34.setGeometry(QtCore.QRect(70, 100, 121, 23))
        self.pushButton_34.setObjectName("pushButton_34")
        self.JogMode_2 = QtWidgets.QGroupBox(Dialog)
        self.JogMode_2.setGeometry(QtCore.QRect(10, 50, 261, 91))
        self.JogMode_2.setStyleSheet("")
        self.JogMode_2.setAlignment(QtCore.Qt.AlignCenter)
        self.JogMode_2.setObjectName("JogMode_2")
        self.pushButton_20 = QtWidgets.QPushButton(self.JogMode_2)
        self.pushButton_20.setGeometry(QtCore.QRect(250, 190, 75, 23))
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_21 = QtWidgets.QPushButton(self.JogMode_2)
        self.pushButton_21.setGeometry(QtCore.QRect(340, 150, 75, 23))
        self.pushButton_21.setObjectName("pushButton_21")
        self.pushButton_22 = QtWidgets.QPushButton(self.JogMode_2)
        self.pushButton_22.setGeometry(QtCore.QRect(350, 80, 75, 23))
        self.pushButton_22.setObjectName("pushButton_22")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.JogMode_2)
        self.lineEdit_6.setGeometry(QtCore.QRect(60, 30, 61, 20))
        self.lineEdit_6.setInputMask("")
        self.lineEdit_6.setText("")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.JogMode_2)
        self.lineEdit_7.setGeometry(QtCore.QRect(130, 30, 61, 20))
        self.lineEdit_7.setInputMask("")
        self.lineEdit_7.setText("")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.pushButton_33 = QtWidgets.QPushButton(self.JogMode_2)
        self.pushButton_33.setGeometry(QtCore.QRect(90, 60, 71, 21))
        self.pushButton_33.setObjectName("pushButton_33")
        self.JogMode_3 = QtWidgets.QGroupBox(Dialog)
        self.JogMode_3.setGeometry(QtCore.QRect(310, 50, 281, 91))
        self.JogMode_3.setStyleSheet("")
        self.JogMode_3.setAlignment(QtCore.Qt.AlignCenter)
        self.JogMode_3.setObjectName("JogMode_3")
        self.pushButton_30 = QtWidgets.QPushButton(self.JogMode_3)
        self.pushButton_30.setGeometry(QtCore.QRect(250, 190, 75, 23))
        self.pushButton_30.setObjectName("pushButton_30")
        self.pushButton_31 = QtWidgets.QPushButton(self.JogMode_3)
        self.pushButton_31.setGeometry(QtCore.QRect(340, 150, 75, 23))
        self.pushButton_31.setObjectName("pushButton_31")
        self.pushButton_32 = QtWidgets.QPushButton(self.JogMode_3)
        self.pushButton_32.setGeometry(QtCore.QRect(350, 80, 75, 23))
        self.pushButton_32.setObjectName("pushButton_32")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.JogMode_3)
        self.lineEdit_5.setGeometry(QtCore.QRect(60, 40, 61, 20))
        self.lineEdit_5.setInputMask("")
        self.lineEdit_5.setText("")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.pushButton_29 = QtWidgets.QPushButton(self.JogMode_3)
        self.pushButton_29.setGeometry(QtCore.QRect(130, 40, 75, 23))
        self.pushButton_29.setObjectName("pushButton_29")
        self.menuBar = QtWidgets.QWidget(Dialog)
        self.menuBar.setEnabled(True)
        self.menuBar.setGeometry(QtCore.QRect(30, 0, 581, 41))
        self.menuBar.setObjectName("menuBar")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.menuBar)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 10, 571, 40))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_36 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(6)
        self.pushButton_36.setFont(font)
        self.pushButton_36.setIconSize(QtCore.QSize(12, 12))
        self.pushButton_36.setObjectName("pushButton_36")
        self.horizontalLayout_3.addWidget(self.pushButton_36)
        self.pushButton_35 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(6)
        self.pushButton_35.setFont(font)
        self.pushButton_35.setIconSize(QtCore.QSize(12, 12))
        self.pushButton_35.setObjectName("pushButton_35")
        self.horizontalLayout_3.addWidget(self.pushButton_35)
        self.pushButton_24 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(6)
        self.pushButton_24.setFont(font)
        self.pushButton_24.setIconSize(QtCore.QSize(12, 12))
        self.pushButton_24.setObjectName("pushButton_24")
        self.horizontalLayout_3.addWidget(self.pushButton_24)
        self.pushButton_19 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(6)
        self.pushButton_19.setFont(font)
        self.pushButton_19.setIconSize(QtCore.QSize(12, 12))
        self.pushButton_19.setObjectName("pushButton_19")
        self.horizontalLayout_3.addWidget(self.pushButton_19)
        self.pushButton_37 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(6)
        self.pushButton_37.setFont(font)
        self.pushButton_37.setIconSize(QtCore.QSize(12, 12))
        self.pushButton_37.setObjectName("pushButton_37")
        self.horizontalLayout_3.addWidget(self.pushButton_37)
        self.pushButton_38 = QtWidgets.QPushButton(Dialog)
        self.pushButton_38.setGeometry(QtCore.QRect(0, 10, 71, 21))
        self.pushButton_38.setBaseSize(QtCore.QSize(1, 2))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.pushButton_38.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Hamburger_icon.svg.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_38.setIcon(icon1)
        self.pushButton_38.setIconSize(QtCore.QSize(12, 12))
        self.pushButton_38.setObjectName("pushButton_38")

        self.menuVisible = True
        self.pushButton_38.clicked.connect(self.toggle_menu)


        self.pushButton.clicked.connect(lambda: motors.joystick(2))

        self.pushButton_8.clicked.connect(lambda: motors.joystick(3))
        self.pushButton_9.clicked.connect(lambda: motors.reset())
        self.pushButton_3.clicked.connect(lambda: motors.joystick(0))
        self.pushButton_2.clicked.connect(lambda: motors.joystick(2))
        self.pushButton_4.clicked.connect(lambda: motors.joystick(1))




        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):    
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.JogMode.setTitle(_translate("Dialog", "Jog Mode"))
        self.pushButton.setText(_translate("Dialog", "UP"))
        self.pushButton_5.setText(_translate("Dialog", "PushButton"))
        self.pushButton_6.setText(_translate("Dialog", "PushButton"))
        self.pushButton_7.setText(_translate("Dialog", "PushButton"))
        self.pushButton_8.setText(_translate("Dialog", "DOWN"))
        self.pushButton_9.setText(_translate("Dialog", "HOME"))
        self.pushButton_3.setText(_translate("Dialog", "LEFT"))
        self.pushButton_2.setText(_translate("Dialog", "STOP"))
        self.pushButton_4.setText(_translate("Dialog", "RIGHT"))
        self.groupBox.setTitle(_translate("Dialog", "Single Point Sampling"))
        self.lineEdit.setPlaceholderText(_translate("Dialog", "Samples"))
        self.lineEdit_2.setPlaceholderText(_translate("Dialog", "Frequency"))
        self.lineEdit_3.setPlaceholderText(_translate("Dialog", "Iteration"))
        self.lineEdit_4.setPlaceholderText(_translate("Dialog", "File Name"))
        self.pushButton_34.setText(_translate("Dialog", "ADQUIRE DATA"))
        self.JogMode_2.setTitle(_translate("Dialog", "Coordinate Position"))
        self.pushButton_20.setText(_translate("Dialog", "PushButton"))
        self.pushButton_21.setText(_translate("Dialog", "PushButton"))
        self.pushButton_22.setText(_translate("Dialog", "PushButton"))
        self.lineEdit_6.setPlaceholderText(_translate("Dialog", "X Position"))
        self.lineEdit_7.setPlaceholderText(_translate("Dialog", "Z Position"))
        self.pushButton_33.setText(_translate("Dialog", "SUBMIT"))
        self.JogMode_3.setTitle(_translate("Dialog", "Step Size in Millimeters "))
        self.pushButton_30.setText(_translate("Dialog", "PushButton"))
        self.pushButton_31.setText(_translate("Dialog", "PushButton"))
        self.pushButton_32.setText(_translate("Dialog", "PushButton"))
        self.lineEdit_5.setPlaceholderText(_translate("Dialog", "Milimiter"))
        self.pushButton_29.setText(_translate("Dialog", "SUBMIT"))
        self.pushButton_36.setText(_translate("Dialog", "MAIN"))
        self.pushButton_35.setText(_translate("Dialog", "DATA"))
        self.pushButton_24.setText(_translate("Dialog", "JOG MODE "))
        self.pushButton_19.setText(_translate("Dialog", "DATA COLLECTION"))
        self.pushButton_37.setText(_translate("Dialog", "DATA VIZ"))
        self.pushButton_38.setText(_translate("Dialog", "MENU"))


    def toggle_menu(self):
        self.menuVisible = not self.menuVisible
        self.menuBar.setVisible(self.menuVisible)
        self.pushButton_38.setText("Hide Menu" if self.menuVisible else "Show Menu")

    def jog_mode(self):

        self.pushButton


if __name__ == "__main__":
    import sys
    from PyQt5 import QtWidgets 

    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()  
    ui.setupUi(Dialog)
    
    Dialog.show()
    sys.exit(app.exec_()) 